import './style.css';

document.querySelector('#app').innerHTML = `
<header class="site-header"><a class="wordmark" href="#top">yashasvi<span>.shailly</span></a><nav class="desktop-nav"><a href="#products">Products</a><a href="#media">Media</a><a href="#testimonials">Testimonials</a><a href="#about">About</a><details><summary>More</summary><div class="more-menu"><a href="#work">How I work</a><a href="#projects">Projects</a><a href="#writing">Writing</a></div></details></nav><a class="hello-link" href="mailto:hello@yashasvishailly.com">Say hello <span>↗</span></a></header>
<main id="top"><section class="hero"><div class="eyebrow"><span class="dot"></span> Free tool</div><h1>The One Look</h1><p class="intro">One look shows what a first time customer trusts, what they miss, and what makes them leave before they ever meet you.</p><form id="look-form" class="look-form"><div class="field-grid"><label>Website<input name="website" type="url" placeholder="yourcompany.com" required/></label><label>Email<input name="email" type="email" placeholder="you@company.com" required/></label></div><label class="consent"><input name="consent" type="checkbox" required/><span>I consent to share my email and allow Yashasvi to use it for exclusive launches or content. I have read the <a href="#privacy">privacy policy</a>.</span></label><button class="primary-button" type="submit">Run the look <span>↗</span></button><p class="form-note" id="form-note" role="status"></p></form></section>
<section class="results" id="results" aria-live="polite"><div class="score-wrap"><div class="score" id="score">0<span>/100</span></div><p>First impression score</p></div><div class="signals"><article><span class="signal-number">01</span><h2>What a first time visitor trusts</h2><p>What makes the business feel credible before a new visitor takes a risk.</p></article><article><span class="signal-number">02</span><h2>What they miss</h2><p>The value, proof, or next step that disappears on a fast first read.</p></article><article><span class="signal-number">03</span><h2>What makes them leave</h2><p>The quiet friction that stops momentum before a conversation begins.</p></article><article><span class="signal-number">04</span><h2>Newest public signal</h2><p>The most recent visible signal a first-time visitor can find.</p></article><article><span class="signal-number">05</span><h2>What is costing you the most</h2><p>The single outside-read issue with the greatest effect on momentum.</p></article></div></section>
<section class="after-read" id="about"><p class="eyebrow">The outside read</p><h2>You now have the outside read.</h2><p>If this is just a page problem, fix the page. If the same confusion shows up in sales calls, team decisions, product priorities, and founder time, find the bottleneck underneath.</p><a class="text-link" href="mailto:hello@yashasvishailly.com">Find the real bottleneck <span>→</span></a></section></main>
<footer><a href="#top" class="wordmark">yashasvi<span>.shailly</span></a><p>The One Look reads your public pages only and reports what a first time customer would perceive. It is a first impression, and only that. It is not an audit, a security assessment, professional advice, or a performance guarantee.</p><a href="#privacy">Privacy</a></footer>`;

const form = document.querySelector('#look-form'); const note = document.querySelector('#form-note'); const results = document.querySelector('#results'); const score = document.querySelector('#score');
form.addEventListener('submit', (event) => { event.preventDefault(); const website = new FormData(form).get('website').replace(/^https?:\/\//, '').replace(/\/$/, ''); note.textContent = `Reading ${website}…`; const button = form.querySelector('button'); button.disabled = true; let value = 0; const timer = setInterval(() => { value += 5; score.innerHTML = `${value}<span>/100</span>`; if (value >= 78) { clearInterval(timer); note.textContent = 'Your first-impression read is ready.'; button.disabled = false; results.classList.add('is-ready'); results.scrollIntoView({ behavior:'smooth', block:'center' }); } }, 25); });
